DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS participation_requests CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR NOT NULL,
    email VARCHAR NOT NULL,
    CONSTRAINT uq_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    CONSTRAINT uq_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat REAL NOT NULL,
    lon REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS events
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    initiator_user_id     BIGINT                      NOT NULL,
    category_id           BIGINT                      NOT NULL,
    location_id           BIGINT                      NOT NULL,

    title                 VARCHAR                     NOT NULL,
    annotation            VARCHAR                     NOT NULL,
    description           VARCHAR                     NOT NULL,
    state                 VARCHAR                     NOT NULL,
    date                  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    create_date           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    publish_date          TIMESTAMP WITHOUT TIME ZONE,
    participant_limit     BIGINT default 0,
    paid               BOOLEAN DEFAULT false,
    request_moderation BOOLEAN default false,

    CONSTRAINT fk_event_initiator FOREIGN KEY (initiator_user_id) REFERENCES users (id),
    CONSTRAINT fk_event_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_event_location FOREIGN KEY (location_id) REFERENCES locations (id)
);

CREATE TABLE IF NOT EXISTS participation_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id      BIGINT                      NOT NULL,
    event_id     BIGINT                      NOT NULL,

    status       VARCHAR                     NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT fk_participation_request_requester FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_participation_request_event FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT uc_unique_requester_event UNIQUE (user_id, event_id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title     VARCHAR NOT NULL,
    pinned BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations_events
(
    compilation_id BIGINT,
    event_id       BIGINT,

    CONSTRAINT fk_compilation_id FOREIGN KEY (compilation_id) REFERENCES compilations (id),
    CONSTRAINT fk_event_id FOREIGN KEY (event_id) REFERENCES events (id),

    PRIMARY KEY (compilation_id, event_id)
);
